export default [
  {
    id: "1",
    firstname: "Adam",
  },
  {
    id: "2",
    father: "6",
    mother: "4",
    firstname: "Mitchell",
    middlename: "Lane",
    maidenname: "",
    lastname: "Hillman",
    suffix: "",
    birthdate: "6/26/1988",
    deathdate: "",
    placeofbirth: "Fairfax, VA",
    placeofdeath: "",
    religion: "Catholic",
    notes: "",
  },
  {
    id: "3",
    father: "2",
    mother: "5",
    firstname: "Patrick",
    middlename: "Ronald",
    maidenname: "",
    lastname: "Hillman",
    suffix: "II",
    birthdate: "4/9/2014",
    deathdate: "",
    placeofbirth: "Charlottesville, VA",
    placeofdeath: "",
    religion: "Catholic",
    notes: "",
  },
  {
    id: "4",
    father: "",
    mother: "",
    firstname: "Lanette",
    middlename: "Lynn",
    maidenname: "",
    lastname: "Hillman",
    suffix: "",
    birthdate: "3/15/1963",
    deathdate: "",
    placeofbirth: "Iowa",
    placeofdeath: "",
    religion: "Baptist",
    notes: "",
  },
  {
    id: "5",
    father: "12",
    mother: "13",
    firstname: "Yvonne",
    middlename: "Elizabeth Marie",
    maidenname: "Beaty",
    lastname: "Hillman",
    suffix: "",
    birthdate: "8/8/1988",
    deathdate: "",
    placeofbirth: "Bedford, VA",
    placeofdeath: "",
    religion: "Catholic",
    notes: "",
  },
  {
    id: "6",
    father: "26",
    mother: "",
    firstname: "Patrick",
    middlename: "Ronald",
    maidenname: "",
    lastname: "Hillman",
    suffix: "",
    birthdate: "4/6/1964",
    deathdate: "",
    placeofbirth: "Vienna, VA",
    placeofdeath: "",
    religion: "Baptist",
    notes: "",
  },
  {
    id: "7",
    father: "2",
    mother: "5",
    firstname: "Alice",
    middlename: "Love",
    maidenname: "",
    lastname: "Hillman",
    suffix: "",
    birthdate: "2/10/2016",
    deathdate: "",
    placeofbirth: "Charlottesville, VA",
    placeofdeath: "",
    religion: "Catholic",
    notes: "",
  },
  {
    id: "8",
    father: "2",
    mother: "5",
    firstname: "Augsutine",
    middlename: "Marshall",
    maidenname: "",
    lastname: "Hillman",
    suffix: "",
    birthdate: "8/8/2018",
    deathdate: "",
    placeofbirth: "Charlottesville, VA",
    placeofdeath: "",
    religion: "Catholic",
    notes: "",
  },
  {
    id: "9",
    father: "6",
    mother: "4",
    firstname: "Miles",
    middlename: "Lary",
    maidenname: "",
    lastname: "Hillman",
    suffix: "",
    birthdate: "1995",
    deathdate: "",
    placeofbirth: "Iowa",
    placeofdeath: "",
    religion: "Baptist",
    notes: "",
  },
  {
    id: "10",
    father: "6",
    mother: "4",
    firstname: "Major",
    middlename: "Lance",
    maidenname: "",
    lastname: "Hillman",
    suffix: "",
    birthdate: "1993",
    deathdate: "",
    placeofbirth: "Cairo, Egypt",
    placeofdeath: "",
    religion: "Baptist",
    notes: "",
  },
  {
    id: "11",
    father: "6",
    mother: "4",
    firstname: "Marshall",
    middlename: "Lear",
    maidenname: "",
    lastname: "Hillman",
    suffix: "",
    birthdate: "12/1/1990",
    deathdate: "",
    placeofbirth: "Cairo, Egypt",
    placeofdeath: "",
    religion: "",
    notes: "",
  },
  {
    id: "12",
    father: "",
    mother: "",
    firstname: "Randy",
    middlename: "",
    maidenname: "",
    lastname: "Beaty",
    suffix: "",
    birthdate: "",
    deathdate: "",
    placeofbirth: "",
    placeofdeath: "",
    religion: "",
    notes: "",
  },
  {
    id: "13",
    father: "",
    mother: "",
    firstname: "Sandy",
    middlename: "",
    maidenname: "",
    lastname: "Beaty",
    suffix: "",
    birthdate: "",
    deathdate: "",
    placeofbirth: "",
    placeofdeath: "",
    religion: "",
    notes: "",
  },
  {
    id: "14",
    father: "12",
    mother: "13",
    firstname: "Josiah",
    middlename: "",
    maidenname: "",
    lastname: "Beaty",
    suffix: "",
    birthdate: "",
    deathdate: "",
    placeofbirth: "",
    placeofdeath: "",
    religion: "",
    notes: "",
  },
  {
    id: "15",
    father: "14",
    mother: "",
    firstname: "James",
    middlename: "Alpha",
    maidenname: "",
    lastname: "Beaty",
    suffix: "",
    birthdate: "9/2018",
    deathdate: "",
    placeofbirth: "",
    placeofdeath: "",
    religion: "",
    notes: "",
  },
  {
    id: "17",
    father: "44",
    mother: "",
    firstname: "Frances",
    middlename: "Duane",
    maidenname: "",
    lastname: "Hillman",
    suffix: "",
    birthdate: "2/8/1834",
    deathdate: "",
    placeofbirth: "Avon Springs, New York",
    placeofdeath: "",
    religion: "",
    notes: "",
  },
  {
    id: "18",
    father: "",
    mother: "",
    firstname: "Josephine",
    middlename: "L",
    maidenname: "Hebard",
    lastname: "Hillman",
    suffix: "",
    birthdate: "1834",
    deathdate: "",
    placeofbirth: "Coulterville, Illinois",
    placeofdeath: "",
    religion: "Presbyterian",
    notes: "",
  },
  {
    id: "23",
    father: "",
    mother: "",
    firstname: "Mary Jane",
    middlename: "",
    maidenname: "McNabb",
    lastname: "Miller",
    suffix: "",
    birthdate: "7/5/1840",
    deathdate: "",
    placeofbirth: "Ohio",
    placeofdeath: "",
    religion: "Mennonite",
    notes: "",
  },
  {
    id: "24",
    father: "22",
    mother: "23",
    firstname: "Minnie",
    middlename: "May",
    maidenname: "Miller",
    lastname: "Hebard",
    suffix: "",
    birthdate: "5/1/1870",
    deathdate: "",
    placeofbirth: "Osborne, Ohio",
    placeofdeath: "",
    religion: "",
    notes: "",
  },
  {
    id: "28",
    father: "",
    mother: "",
    firstname: "Adelheid",
    middlename: "",
    maidenname: "",
    lastname: "Kranauer",
    suffix: "",
    birthdate: "",
    deathdate: "",
    placeofbirth: "",
    placeofdeath: "",
    religion: "Catholic",
    notes: "",
  },
  {
    id: "30",
    father: "",
    mother: "",
    firstname: "Fritz",
    middlename: "",
    maidenname: "",
    lastname: "Stucki",
    suffix: "",
    birthdate: "",
    deathdate: "",
    placeofbirth: "",
    placeofdeath: "",
    religion: "Swiss Reformed",
    notes: "",
  },
  {
    id: "31",
    father: "",
    mother: "",
    firstname: "Elisabeth",
    middlename: "",
    maidenname: "",
    lastname: "Schneeberger",
    suffix: "",
    birthdate: "",
    deathdate: "",
    placeofbirth: "",
    placeofdeath: "",
    religion: "Swiss Reformed",
    notes: "",
  },
  {
    id: "32",
    father: "31",
    mother: "30",
    firstname: "Emma",
    middlename: "",
    maidenname: "Stucki",
    lastname: "Kranauer",
    suffix: "",
    birthdate: "",
    deathdate: "",
    placeofbirth: "",
    placeofdeath: "",
    religion: "Swiss Reformed, Lutheran",
    notes: "",
  },
  {
    id: "38",
    father: "25",
    mother: "33",
    firstname: "Sylvia",
    middlename: "Yvonne",
    maidenname: "",
    lastname: "Hillman",
    suffix: "",
    birthdate: "12/1/1932",
    deathdate: "",
    placeofbirth: "New York, New York",
    placeofdeath: "",
    religion: "",
    notes: "",
  },
  {
    id: "39",
    father: "",
    mother: "",
    firstname: "John",
    middlename: "",
    maidenname: "",
    lastname: "Hillman",
    suffix: "",
    birthdate: "1651",
    deathdate: "",
    placeofbirth: "London(?), Englad",
    placeofdeath: "Martha's Vineyard, Mass.",
    religion: "",
    notes: "",
  },
  {
    id: "42",
    father: "41",
    mother: "",
    firstname: "Benjamin",
    middlename: "",
    maidenname: "",
    lastname: "Hillman",
    suffix: "Jr.",
    birthdate: "1727",
    deathdate: "",
    placeofbirth: "New Bedford, Mass.",
    placeofdeath: "Louville, N.Y.",
    religion: "",
    notes: "",
  },
  {
    id: "43",
    father: "42",
    mother: "",
    firstname: "David",
    middlename: "",
    maidenname: "",
    lastname: "Hillman",
    suffix: "",
    birthdate: "1778",
    deathdate: "1870",
    placeofbirth: "Martha's Vineyard, Mass.",
    placeofdeath: "Aram, N.Y.",
    religion: "",
    notes: "",
  },
  {
    id: "44",
    father: "43",
    mother: "",
    firstname: "David",
    middlename: "C",
    maidenname: "",
    lastname: "Hillman",
    suffix: "",
    birthdate: "1806",
    deathdate: "1891",
    placeofbirth: "Louville, N.Y",
    placeofdeath: "Clinton, Mich.",
    religion: "",
    notes: "",
  },
  {
    id: "46",
    father: "26",
    mother: "",
    firstname: "Richard",
    middlename: "F",
    maidenname: "",
    lastname: "Hillman",
    suffix: "",
    birthdate: "1962",
    deathdate: "",
    placeofbirth: "Fairfax Co., VA",
    placeofdeath: "",
    religion: "",
    notes: "",
  },
  {
    id: "47",
    father: "46",
    mother: "",
    firstname: "Richard",
    middlename: "",
    maidenname: "",
    lastname: "Hillman",
    suffix: "Jr.",
    birthdate: "1992",
    deathdate: "",
    placeofbirth: "Fairfax Co., VA",
    placeofdeath: "",
    religion: "",
    notes: "",
  },
  {
    id: "16",
    father: "14",
    mother: "",
    firstname: "John",
    middlename: "",
    maidenname: "",
    lastname: "Beaty",
    suffix: "",
    birthdate: "9/2018",
    deathdate: "",
    placeofbirth: "",
    placeofdeath: "",
    religion: "",
    notes: "*cannot confirm with second source at this time",
  },
  {
    id: "41",
    father: "39",
    mother: "",
    firstname: "Benjamin",
    middlename: "",
    maidenname: "",
    lastname: "Hillman",
    suffix: "",
    birthdate: "1690",
    deathdate: "1745",
    placeofbirth: "Martha's Vineyard, Mass.",
    placeofdeath: "Dartsmouth, Mass.",
    religion: "",
    notes: "*cannot confirm with second source at this time",
  },
  {
    id: "26",
    father: "25",
    mother: "33",
    firstname: "Richard",
    middlename: '"Dick"',
    maidenname: "",
    lastname: "Hillman",
    suffix: "",
    birthdate: "7/9/1930",
    deathdate: "",
    placeofbirth: "New York, New York",
    placeofdeath: "",
    religion: "Methodists, Baptist, Seventh Day Adventists, Pentecostal",
    notes:
      "Christian Profile of Richard Hillman\nInterview by his daughter Sylvia Westerlund 10/1/1993\nTyped and edited by his Grandson Mitchell Hillman 10/9/2021\n\n1942-3\n\nAge 12-13, I attended a local Methodist Church in Catonsville, Md. Neither of my parents or sister attended any church so all of my motive was on my own .\n\n1948\n\nAge 18, I received salvation in Washington D.C. at a Baptist Church. The church do not follow through with teaching and fellowship and neither did I and I dropped out of church shortly.\n\n1951\n\nAge 21, I was introduced to (and joined) the Seventh Day Adventist Church by first wife to be. That time I first learned about tithing. I remained in the S.D.N. Church for about 6 years.\n\n1957\n\n(1965 first wife and I divorced 9/65)\n(1968 married second wife 9/68)\n\nAge 27, I returned to the Methodist Church for the next 23 years. 1966 the tithing principal was being taught so I started the practice and continued ever since.\n\n1980\n\nAge 50, I left the methodist church (3rd church since 1957) because the pastors belief Jesus was one of the ways God provided for salvation as opposed to the only was of salvation. My second wife left this church also approximately 6 months before me and she introduced me to the charismatic non denominational living room fellowship meeting. I met the person who later became my third wife there. I joined an inner city charismatic Baptist Church.\n\n1981\n\n(My second wife died of cancer 7/81)\n\n1982\n\nI married my 3rd wife and we went to Uganda, East Africa on a short term mission trip. \n\nWe left the Washington D.C. area to attend a charismatic non-denominational Bible training school in Broken Arrow, Oklahoma.\n\n1984-88\n\nI (we) returned to mission work in Kenya and Uganda, East Africa. I (we) were members and being supported by a charismatic non-denominational fellowship in Falls Church, Virginia. \n\n1990\nAge 60, I (we) went to Chapel Hill, NC to work with a black charismatic non-denominational Church. We were invited to set up a mission board and help in the church as needed. After 8 months no progress had been made so we returned to secular jobs. We attended a local charismatic non-denominational church. \n\n1991-93\n\nI (we) returned north to Ellicott City and Columbia Maryland and joined the Southern Baptist Church in Columbia, Maryland.",
  },
  {
    id: "25",
    father: "19",
    mother: "24",
    firstname: "Francis",
    middlename: "Marion",
    maidenname: "",
    lastname: "Hillman",
    suffix: "",
    birthdate: "6/24/1896",
    deathdate: "1/9/1981",
    placeofbirth: "Reno, Nevada",
    placeofdeath: "Saranac Lake, New York",
    religion: "Quaker",
    notes:
      "Francis Marion Hillman\nElizabeth Kranauer Hillman \n\nBorn in Reno, Nevada, on June 24, 1896, Francis was the son of Fred and Minnie May Miller Heard. His father was born in Machester, Michigan, on June 13, 1863 and his mother in Osborn, Ohio, on May 1, 1870. His paternal grandparents were Francis Diane and Josephine L. Heard, Francis Duane being born in Avon Springs, New York, on February 8, 1834, and Josephine in Coulterville, Illinois that same year. His grandparents on his mother’s side were both from Ohio. John Erb Miller was born August 22, 1833 and Mary Jane McNabb Miller on July 5, 1840.\n\nDuring the First World War, Francis was an aviation cadet. However, before his training was completed, the war was over and he was discharged. Upon his discharge in 1918 he came to Washington, D.C.\n\nAbout two years later, when he was 24 years old, he began his lifelong career with Standard Oil Company (now known as Exxon.) He worked on oil tankers, beginning as a merchant seaman. As the years passed, he rose in rank to first mate and eventually captain. He retired in 1957, at the age of 63.\n\nIn 1929, Francis was living in the New York City metropolitan area. It was here that he married Elizabeth Kranauer on September 1, 1929. The daughter of Joseph J. (Jr.) and Emma Stucki Kranauer, Elizabeth was born in Morges, Switzerland, on November 4, 1906. When she was two years old she immigrated to America with her parents, who settled in Washington, D.C.\n\nGrowing up in Washington, Elizabeth received her education in the public schools there. In 1925 she graduated from McKinley Technical High School in the northeastern section of the city.\n\nAfter their marriage, Francis and Elizabeth remained in New York, where they had two children, Richard, born July 9, 1930, and Sylvia Yvonne, born December 1, 1932. It was around this time that Elizabeth contracted tuberculosis; several times while her children were growing up she had to be hospitalized because of the disease.\n\nIn 1938, Francis and his family returned to Washington, D.C.\n\nWhen World War II began, Francis’ experience with Standard Oil prepared him well for service with the U.S. Navy. During this war he was the captain of a naval oil tanker in the South Pacific. By the war’s end, he had attained the rank of commander.\n\nIn 1955, Francis and Elizabeth left Washington, moving to the more healthful climate of Saranac Lake, New York.\n\nAs a youth Elizabeth attended Concordia Lutheran Church; in her later years she became quite active in the Methodist Church. Francis was a Quaker, but was not actively involved with any church.\n\nFrancis enjoyed helping out with organizations of which he was a member–the American Red Cross, the Humane Society, and Alcoholics Anonymous. Elizabeth, too, was a Red. Ross volunteer, and also helped in the Meals on Wheels program.\n\nFrancis died on January 9, 1981, at Saranac Lake, New York. He was 83 years old. His cause of death was cancer of the bladder, possibly the result of a life-long habit of smoking. His son states, “During my father’s employed life he was on the move much of the time. Only after retirement was I able to spend time visiting with him.”\n\nTwo years later, in June 1983, at Saranac Lake, Elizabeth suffered a fatal heart attack. She was 76 years old. Her son recalls, “I lived with my mother until age 21 except for two occasions when she was hospitalized with TB. We were close all my life up to one or two weeks before he death.” When asked what gave his mother particular pleasure in life, he responded, \\I think seeing her children doing well.”–Richard Hillman, respondent",
  },
  {
    id: "19",
    father: "17",
    mother: "18",
    firstname: "Fred",
    middlename: "Hebard",
    maidenname: "",
    lastname: "Hillman",
    suffix: "",
    birthdate: "6/13/1863",
    deathdate: "2/8/1954",
    placeofbirth: "Lyons, Mich.",
    placeofdeath: "Washington, D.C",
    religion: "Presbyterian",
    notes:
      "Fred Hebard Hillman\n\n1889-1900\n\nFred Hebard Hillman was the first botanist to join the staff of the University of Nevada. He was born in Lyons, Michigan on June 13. He received a B.S. degree at Michigan Agriculture College in 1888 and M.S. degree in entomology in 1889.\n\nHe taught botany and entomology at the Nevada Experiment Station 1889 to 1900. Experiment Station Bulletin No. 24. November 1892– The Early Flora of the Trclee Meadows” by Hillman was used as a botany guide. \n\nOn August 30, 1890, the second Morrill Act was passed which became the source of funds for the study of weed seeds. Hillman who was energetic, enthusiastic, and artistic, began a series of seed illustrations, working out the distinguishing botanical characteristics and devising means of identifying them under moderate magnification. His drawings were technically perfect and beautiful. Upon publication of Eperiment Bulletin No. 24 in 1900, entitled “Clover Seed and their Impurities” by Hillman. The University and Experiment Station received their first scientific recognition. \n\nHis study came at a time when American agriculture was becoming of the importance of pure seed. This work led to immediate employment of Hillman by the United States Department of Agriculture of Washington D.D where he had a lifelong career. He became known as the best illustrator of seed in the United States. Hillman retired from government service June 26, 1933 and he collaborated without compoensation until October 23, 1944. He died at Washington D.C on February 8, 1954",
  },
  {
    id: "35",
    father: "",
    mother: "",
    firstname: "Benjamin",
    middlename: "L",
    maidenname: "",
    lastname: "Hillman",
    suffix: "",
    birthdate: "2/5/1801",
    deathdate: "6/21/1884",
    placeofbirth: "",
    placeofdeath: "",
    religion: "",
    notes: "grave at Union Cem.",
  },
  {
    id: "33",
    father: "30",
    mother: "32",
    firstname: "Elizabeth",
    middlename: "",
    maidenname: "Kranauer",
    lastname: "Hillman",
    suffix: "",
    birthdate: "11/4/1906",
    deathdate: "6/1983",
    placeofbirth: "Morges, Switzerland",
    placeofdeath: "Saranac Lake, New York",
    religion: "Methodist, Lutheran",
    notes:
      "immigrated to America with her parents when she was two years old. Settled in Washington D.C.\n\nGrowing up in Washington, Elizabeth received her education in the public schools there. In 1925 she graduated from McKinley Technical High School in the northeastern section of the city.\n\nwas pressured to attend church classes",
  },
  {
    id: "29",
    father: "27",
    mother: "28",
    firstname: "Joseph",
    middlename: "J",
    maidenname: "",
    lastname: "Kranauer",
    suffix: "Jr.",
    birthdate: "",
    deathdate: "",
    placeofbirth: "",
    placeofdeath: "",
    religion: "Catholic",
    notes: "left the church. felt it used its members",
  },
  {
    id: "37",
    father: "35",
    mother: "36",
    firstname: "Mather",
    middlename: "B",
    maidenname: "",
    lastname: "Hillman",
    suffix: "",
    birthdate: "1826",
    deathdate: "2/18/1954",
    placeofbirth: "",
    placeofdeath: "",
    religion: "",
    notes: "son of B.L. and Esther Hillman. Burried Union Cem.",
  },
  {
    id: "27",
    father: "",
    mother: "",
    firstname: "Joseph",
    middlename: "",
    maidenname: "",
    lastname: "Kranauer",
    suffix: "Sr.",
    birthdate: "",
    deathdate: "",
    placeofbirth: "",
    placeofdeath: "",
    religion: "Catholic",
    notes: "was faithful to the church",
  },
  {
    id: "22",
    father: "",
    mother: "",
    firstname: "John",
    middlename: "Erb",
    maidenname: "",
    lastname: "Miller",
    suffix: "",
    birthdate: "8/22/1833",
    deathdate: "",
    placeofbirth: "Ohio",
    placeofdeath: "",
    religion: "Mennonite",
    notes: "was marred by the cruelty of the Civil War",
  },
  {
    id: "36",
    father: "",
    mother: "",
    firstname: "Esther",
    middlename: "",
    maidenname: "",
    lastname: "Hillman",
    suffix: "",
    birthdate: "1800",
    deathdate: "4/18/1850",
    placeofbirth: "",
    placeofdeath: "",
    religion: "",
    notes: "wfie of B.L. Hillman, burried Union Cem.",
  },
  {
    id: "34",
    father: "",
    mother: "",
    firstname: "Rachel",
    middlename: "N",
    maidenname: "",
    lastname: "Hillman",
    suffix: "",
    birthdate: "12/21/1814",
    deathdate: "11/2/1986",
    placeofbirth: "",
    placeofdeath: "",
    religion: "",
    notes: "Wife of Benjamin Hillman. Burried in Union Cem.",
  },
];
